server:
  port: 9000
spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071"
#  cloud:
#    bus:
#      enabled: false
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

info:
  app:
    name: "cards"
    description: "Cards Application"
    version: "1.0.0"

logging:
  level:
    com:
      ft:
        cards: DEBUG