build:
  version: "3.0"

loans:
  message: "Welcome to Bank loans related prod APIs "
  contactDetails:
    name: "Developer"
    email: "prod-load@ft.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934