server:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"
#  cloud:
#    bus:
#      enabled: false

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"


  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8072/eureka/

info:
  app:
    name: "accounts"
    description: "Accounts Application"
    version: "1.0.02"