services:
  rabbitmq:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      command: "start-dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"